manifestVersion: 1.0

projects:
  - name: forward-change-guardian
    path: project

environmentGroups:
  - name: sandbox
    environments:
      - name: sandbox
        url:
          type: environment
          value: DYNATRACE_ENVIRONMENT_URL
        auth:
          platformToken:
            type: environment
            name: DYNATRACE_PLATFORM_TOKEN
