apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forward-dynatrace-state
  labels:
    app.kubernetes.io/part-of: forward-dynatrace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

