apiVersion: v1
kind: Secret
metadata:
  name: forward-dynatrace-credentials
  labels:
    app.kubernetes.io/name: forward-dynatrace-connector
    app.kubernetes.io/part-of: forward-dynatrace
type: Opaque
stringData:
  forward-user: "<user>"
  forward-password: "<password-or-token>"
