apiVersion: v1
kind: ConfigMap
metadata:
  name: forward-dynatrace-check-health-config
  labels:
    app.kubernetes.io/name: forward-dynatrace-check-health
    app.kubernetes.io/part-of: forward-dynatrace
data:
  forward-base-url: "https://forward.example.com"
  forward-network-id: "<network-id>"
  dynatrace-environment-url: "https://your-environment-id.apps.dynatrace.com/"

